FROM {{ os_name }}:{{ os_version }}

LABEL tailor="environment"

SHELL ["/bin/bash", "-c"]

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install --no-install-recommends -y \
    locales curl gnupg sudo ccache software-properties-common expect
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

# Configure ccache
RUN apt-get update && apt-get install --no-install-recommends -y ccache && \
    ccache -M 5G && \
    ccache --set-config=cache_dir=/ccache

# Install apt s3 support
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    apt-transport-s3

# Create auth config file for accesing s3 via apt
RUN echo "AccessKeyId = $AWS_ACCESS_KEY_ID" | tee /etc/apt/s3auth.conf && \
    echo "SecretAccessKey = $AWS_SECRET_ACCESS_KEY" | tee -a /etc/apt/s3auth.conf

# Add package mirror
# TODO(pbovbel) read this from configuration
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 142D5F1683E1528B && \
    echo "deb [arch=amd64] s3://{{ bucket_name }}/{{ release_label }}/ubuntu {{ os_version }}-mirror main" >> /etc/apt/sources.list && \
    apt-get update && apt-get dist-upgrade -y

# Install colcon build tool
RUN apt-get update && apt-get install --no-install-recommends -y \
    python3-colcon-common-extensions

# Install build and run dependencies
# TODO(pbovbel) install contrainted versions of packages rather than using 'regex_replace'
RUN apt-get update && RTI_NC_LICENSE_ACCEPTED=yes apt-get install --no-install-recommends -y \
  {{ build_depends | union(run_depends) | sort | join(' ') | regex_replace('\(.*?\)', '') }}

# Create non-root user
RUN groupadd -r tailor && useradd -ms /bin/bash -g tailor -G sudo tailor
USER tailor

RUN mkdir -p /home/tailor && \
    usermod -d /home/tailor tailor

RUN mkdir -p /home/tailor/.ros
ENV ROS_HOME /home/tailor/.ros

RUN ccache -M 5G && \
    ccache --set-config=cache_dir=/ccache
