import argparse
import os
import pathlib
import pwd
import shutil
import subprocess
import sys

from typing import List, Tuple


def _source_setup(setup_script: pathlib.Path, base_env: dict) -> dict:
    """Source a colcon setup.bash in a clean shell and return the resulting environment."""
    if not setup_script.exists():
        return dict(base_env)
    result = subprocess.run(
        ["bash", "--norc", "--noprofile", "-c",
         f"source '{setup_script}' 2>/dev/null; env"],
        capture_output=True, text=True, env=base_env,
    )
    if result.returncode != 0:
        return dict(base_env)
    captured = {}
    for line in result.stdout.splitlines():
        if "=" in line:
            k, _, v = line.partition("=")
            captured[k] = v
    return captured


def _seed_workspace_setup(install_path: pathlib.Path, *underlay_prefixes: pathlib.Path) -> None:
    """Write a setup.bash that chains through underlays, replicating what a previous build leaves.

    On a fresh workspace colcon has no underlay chain and can't find apt-installed deps.
    This pre-seeds setup.bash identically to what colcon would generate after a build.
    """
    setup_bash = install_path / "setup.bash"
    if setup_bash.exists():
        return
    install_path.mkdir(parents=True, exist_ok=True)
    lines = [
        "# generated by build_packages (underlay seed)\n",
        "_colcon_prefix_chain_bash_source_script() {\n",
        "  [ -f \"$1\" ] && . \"$1\" || echo \"not found: \\\"$1\\\"\" 1>&2\n",
        "}\n",
    ]
    for prefix in underlay_prefixes:
        if prefix and prefix.exists():
            lines += [
                f"COLCON_CURRENT_PREFIX=\"{prefix}\"\n",
                "_colcon_prefix_chain_bash_source_script \"$COLCON_CURRENT_PREFIX/local_setup.bash\"\n",
            ]
    lines += [
        "COLCON_CURRENT_PREFIX=\"$(builtin cd \"`dirname \"${BASH_SOURCE[0]}\"`\" > /dev/null && pwd)\"\n",
        "_colcon_prefix_chain_bash_source_script \"$COLCON_CURRENT_PREFIX/local_setup.bash\"\n",
        "unset COLCON_CURRENT_PREFIX\n",
        "unset _colcon_prefix_chain_bash_source_script\n",
    ]
    setup_bash.write_text("".join(lines))

from . import YamlLoadAction
from .blossom import Graph, GraphPackage


def get_build_list(graph: Graph, ros_distro: str, recipe: dict | None = None, rebuild_all: bool = False) -> Tuple[List[GraphPackage], List[GraphPackage]]:
    if recipe:
        root_packages = recipe["distributions"][ros_distro]["root_packages"]
    else:
        root_packages = []

    packages, ignore = graph.build_list(ros_distro, root_packages, rebuild_all=rebuild_all)

    return list(packages.values()), list(ignore.values())


def prepend_env_path(env: dict, key: str, value: str):
    if key in env and env[key]:
        env[key] = f"{value}:{env[key]}"
    else:
        env[key] = value

    return env


def main():
    parser = argparse.ArgumentParser(
        description="Build ROS packages that aren't already built"
    )
    parser.add_argument(
        "--recipe",
        action=YamlLoadAction,
        required=True
    )
    parser.add_argument(
        "--graph",
        type=pathlib.Path,
        required=True
    )
    parser.add_argument(
        "--workspace",
        type=pathlib.Path,
        required=True
    )
    parser.add_argument(
        "--ros-distro",
        required=True
    )
    parser.add_argument(
        "--force-packages",
        default=[],
        nargs="+"
    )
    parser.add_argument(
        "--no-clean",
        action="store_true"
    )
    parser.add_argument(
        "--rebuild-all",
        action="store_true"
    )

    args, unknown_args = parser.parse_known_args()

    # Normalize incoming paths so environment variables are deterministic
    # regardless of the caller's current working directory.
    args.workspace = args.workspace.resolve()
    args.graph = args.graph.resolve()

    graph = Graph.from_yaml(args.graph)

    install_path = (
        args.workspace
        / pathlib.Path("install")
        / pathlib.Path(args.ros_distro)
        / pathlib.Path("install")
    )
    build_base = (
        args.workspace
        / pathlib.Path("build")
        / pathlib.Path(args.ros_distro)
        / pathlib.Path("build")
    )
    base_path = args.workspace / pathlib.Path("src") / pathlib.Path(args.ros_distro)
    optinstall_root = (
        args.workspace
        / pathlib.Path("..")
        / pathlib.Path("optinstall")
        / pathlib.Path(graph.organization)
        / pathlib.Path(graph.release_label)
    ).resolve()
    current_optinstall_prefix = optinstall_root / pathlib.Path(args.ros_distro)

    packages_to_build, apt_packages = get_build_list(graph, args.ros_distro, rebuild_all=args.rebuild_all)

    if apt_packages:
        print(f"[APT] Installing {len(apt_packages)} unchanged packages via apt...")
        apt_names = [
            f"{pkg.debian_name(graph.organization, graph.release_label)}={pkg.apt_candidate_version}"
            for pkg in apt_packages
            if pkg.apt_candidate_version
        ]
        if apt_names:
            subprocess.run(["sudo", "-E", "apt-get", "update", "-qq"], check=False)
            apt_result = subprocess.run(
                ["sudo", "-E", "apt-get", "install", "-y", "--no-install-recommends"] + apt_names,
                check=False
            )
            if apt_result.returncode != 0:
                print("[APT] apt-get install failed, falling back to full build")
                apt_packages = []

    cxx_flags = args.recipe["common"]["cxx_flags"]
    cxx_standard = args.recipe["common"]["cxx_standard"]
    python_version = args.recipe["common"]["python_version"]

    venv_bin = str(pathlib.Path(sys.executable).parent)
    rustup_home = os.environ.get("RUSTUP_HOME", "/opt/rust/rustup")
    cargo_home = os.environ.get("CARGO_HOME", "/opt/rust/cargo")
    cargo_bin = str(pathlib.Path(cargo_home) / "bin")
    real_home = pwd.getpwuid(os.getuid()).pw_dir

    # Minimal base: no host env leakage.
    base_env = {
        "PATH": f"{venv_bin}:{cargo_bin}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "HOME": real_home,
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "PYTHONNOUSERSITE": "1",
        "RUSTUP_HOME": rustup_home,
        "CARGO_HOME": cargo_home,
        "RUSTUP_INIT_SKIP_PATH_CHECK": "yes",
    }

    ros1_opt = pathlib.Path(f"/opt/{graph.organization}/{graph.release_label}/ros1")
    ros2_opt = pathlib.Path(f"/opt/{graph.organization}/{graph.release_label}/ros2")

    # Seed the workspace setup.bash with the underlay chain before colcon runs.
    # Without this, a fresh workspace has no chain and colcon can't find apt-installed deps.
    _seed_workspace_setup(install_path, ros1_opt, ros2_opt if args.ros_distro == "ros2" else None)

    # Source installed underlays: ros1 always, then ros2 on top for ros2 builds.
    env = _source_setup(ros1_opt / "setup.bash", base_env)
    print(f"[DEBUG] ros1 setup.bash exists: {(ros1_opt / 'setup.bash').exists()}")
    print(f"[DEBUG] COLCON_CURRENT_PREFIX={env.get('COLCON_CURRENT_PREFIX', '<not set>')}")
    print(f"[DEBUG] after sourcing ros1: ROS_PACKAGE_PATH={env.get('ROS_PACKAGE_PATH', '<not set>')}")
    if args.ros_distro == "ros2":
        env = _source_setup(ros2_opt / "setup.bash", env)
        print(f"[DEBUG] after sourcing ros2: AMENT_PREFIX_PATH={env.get('AMENT_PREFIX_PATH', '<not set>')}")

    # Add stale workspace paths for apt-installed packages to CMAKE_PREFIX_PATH so
    # colcon_ros.prefix_path.catkin detects them as missing and falls back to /opt,
    # matching the local behaviour where these paths persist from a previous full build.
    for pkg in apt_packages:
        prepend_env_path(env, "CMAKE_PREFIX_PATH", str(install_path / pkg.name))

    # Prepend workspace-built and optinstall paths so they shadow /opt packages.
    current_workspace_prefix = install_path
    for prefix in (current_optinstall_prefix, current_workspace_prefix):
        prepend_env_path(env, "LD_LIBRARY_PATH", str(prefix / "lib"))
        prepend_env_path(env, "PYTHONPATH", str(prefix / "lib/python3/dist-packages"))
        prepend_env_path(env, "PKG_CONFIG_PATH", str(prefix / "lib/pkgconfig"))
        prepend_env_path(env, "CMAKE_PREFIX_PATH", str(prefix))
        if args.ros_distro == "ros2":
            prepend_env_path(env, "AMENT_PREFIX_PATH", str(prefix))
        elif args.ros_distro == "ros1":
            prepend_env_path(env, "ROS_PACKAGE_PATH", str(prefix / "share"))

    # Add any additional workspace-built underlay distros (e.g. ros1 built in this run for ros2).
    for underlay in args.recipe["common"]["distributions"][args.ros_distro].get("underlays", []):
        ws_underlay = args.workspace / "install" / underlay / "install"
        opt_underlay = optinstall_root / underlay
        for prefix in (opt_underlay, ws_underlay):
            prepend_env_path(env, "LD_LIBRARY_PATH", str(prefix / "lib"))
            prepend_env_path(env, "PYTHONPATH", str(prefix / "lib/python3/dist-packages"))
            prepend_env_path(env, "PKG_CONFIG_PATH", str(prefix / "lib/pkgconfig"))
            prepend_env_path(env, "CMAKE_PREFIX_PATH", str(prefix))
            if underlay == "ros1":
                prepend_env_path(env, "ROS_PACKAGE_PATH", str(prefix / "share"))
            elif underlay == "ros2":
                prepend_env_path(env, "AMENT_PREFIX_PATH", str(prefix))

    # Build-specific variables (applied last so they cannot be overwritten by setup scripts).
    env.update({k: str(v) for k, v in args.recipe["common"]["distributions"][args.ros_distro]["env"].items()})
    env["ROS_DISTRO_OVERRIDE"] = f"{graph.organization}-{graph.release_label}"
    env["CATKIN_INSTALL_INTO_PREFIX_ROOT"] = "0"
    env["CMAKE_BUILD_PARALLEL_LEVEL"] = "4"
    env["MAKEFLAGS"] = "-j 2"
    env["RELEASE_LABEL"] = graph.release_label
    env["RELEASE_STAMP"] = graph.build_date

    # Construct the colcon command directly
    colcon_command = [
        sys.executable, "-m", "colcon", "package-debian",
        "--graph", str(args.graph),
        "--ros-version", args.ros_distro,
        "--parallel-workers", "4",

        "--base-paths", str(base_path),
        "--build-base", str(build_base),
        "--install-base", str(install_path),
        "--cmake-args",
        f"-DCMAKE_CXX_FLAGS={' '.join(cxx_flags)}",
        f"-DCMAKE_CXX_STANDARD={cxx_standard}",
        "-DCMAKE_CXX_STANDARD_REQUIRED=ON",
        "-DCMAKE_CXX_EXTENSIONS=ON",
        "-DCMAKE_CXX_COMPILER_LAUNCHER=ccache",
        f"-DPYTHON_EXECUTABLE=/usr/bin/python{python_version}",
        "-DCMAKE_VERBOSE_MAKEFILE=ON",
        "-DCHECK_FOR_UPDATES=OFF",
        "-DCMAKE_INSTALL_SYMLINK_SUPPORTED=FALSE",
        "-G", "Ninja",
        "--ament-cmake-args",
        "-DBUILD_TESTING=OFF",
        "--catkin-cmake-args",
        "-DCATKIN_SKIP_TESTING=1",
        "--catkin-skip-building-tests",
        "--event-handlers", "console_cohesion+",
    ]

    if apt_packages:
        colcon_command.append("--skip-apt-available")

    # Add unknown args if any
    colcon_command.extend(unknown_args)

    print("Pre-build Environment:")
    for key, value in env.items():
        print(f"{key}={value}")

    # Print the resolved Cargo path from the build environment for debugging
    # toolchain mismatches in CI containers.
    print(f"Resolved cargo path: {shutil.which('cargo', path=env['PATH'])}")

    print(" ".join(colcon_command))

    build_proc = subprocess.Popen(
        colcon_command,
        env=env
    )

    rc = build_proc.wait()

    if rc != 0:
        # Diagnose package.sh lookup failures: show what's in the workspace install
        # and confirm whether failing packages exist in the /opt underlay.
        print(f"[DEBUG] workspace install contents ({install_path}):")
        if install_path.exists():
            for entry in sorted(install_path.iterdir()):
                print(f"  {entry.name}/")
        else:
            print("  <directory does not exist>")
        print("[DEBUG] apt packages in /opt: checking share dirs")
        for pkg in apt_packages:
            opt_share = ros1_opt / "share" / pkg.name
            ws_share = install_path / pkg.name / "share" / pkg.name / "package.sh"
            print(f"  {pkg.name}: /opt exists={opt_share.exists()}, ws package.sh exists={ws_share.exists()}")

    # Print rosidl type description arguments files so include_paths is visible in CI logs.
    for pkg in packages_to_build:
        args_json = build_base / pkg.name / "rosidl_generator_type_description__arguments.json"
        if args_json.exists():
            print(f"[DEBUG] {args_json}:")
            print(args_json.read_text())

    exit(rc)

if __name__ == "__main__":
    main()
