#!/usr/bin/python3
import argparse
import base64
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
from contextlib import contextmanager
from typing import Any, Mapping
from urllib.parse import urlsplit

import click
import rosdistro
import yaml
from catkin_pkg.package import parse_package
from jinja2 import Environment, StrictUndefined
from vcs2l.commands.import_ import main as vcs_import

from . import YamlLoadAction

PULL_WORKERS = 10
IGNORE_CONTENT = "# Generated by tailor-distro: package excluded by release.packages.\n"


def checkout_url(url: str, github_key: str | None) -> str:
    parsed = urlsplit(url)
    if parsed.hostname == "github.com" and parsed.scheme == "https" and not github_key:
        return f"git@github.com:{parsed.path.lstrip('/')}"
    return url


@contextmanager
def github_authentication(github_key: str | None):
    if not github_key:
        yield
        return
    # Git subprocesses inherit these settings; no token is written to .git/config.
    count = int(os.environ.get("GIT_CONFIG_COUNT", "0"))
    credentials = base64.b64encode(f"x-access-token:{github_key}".encode()).decode()
    settings = {
        f"GIT_CONFIG_KEY_{count}": "http.https://github.com/.extraheader",
        f"GIT_CONFIG_VALUE_{count}": f"Authorization: Basic {credentials}",
        "GIT_CONFIG_COUNT": str(count + 1),
    }
    previous = {key: os.environ.get(key) for key in settings}
    os.environ.update(settings)
    try:
        yield
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def child_directory(parent: pathlib.Path, name: str) -> pathlib.Path:
    if not name or name in (".", "..") or pathlib.Path(name).name != name:
        raise ValueError(f"Invalid repository or distribution directory name: {name!r}")
    path = parent / name
    if path.is_symlink():
        raise ValueError(f"Refusing to use symlinked source directory: {path}")
    return path


def select_repositories(distro, distro_options: Mapping[str, Any], github_key: str | None):
    repositories = {}
    whitelists = {}
    template_env = Environment(undefined=StrictUndefined)
    for name, data in distro.repositories.items():
        release = data.release_repository
        source = data.source_repository
        selected = release or source
        if selected is None or selected.type != "git":
            raise ValueError(f"{name}: a Git source or release repository is required")
        if release and release.version is not None:
            version = template_env.from_string(release.tags["release"]).render(
                package=name,
                upstream=distro_options["upstream"]["name"],
                version=release.version,
            )
        elif source:
            version = source.version
        else:
            raise ValueError(f"{name}: no release pin or source ref is configured")
        repositories[name] = {"type": "git", "url": checkout_url(selected.url, github_key)}
        if version is not None:
            repositories[name]["version"] = version
        if release and release.package_names != [name]:
            whitelists[name] = release.package_names
    return repositories, whitelists


def filter_packages(repo_dir: pathlib.Path, whitelist: list[str]) -> None:
    # Remove only our own old markers; never undo user- or upstream-provided ignores.
    for marker in repo_dir.rglob("COLCON_IGNORE"):
        if not marker.is_symlink() and marker.read_text() == IGNORE_CONTENT:
            marker.unlink()
    if not whitelist:
        return
    for package_xml in sorted(repo_dir.rglob("package.xml")):
        if ".git" in package_xml.relative_to(repo_dir).parts:
            continue
        package = parse_package(str(package_xml))
        if package.name not in whitelist:
            marker = package_xml.parent / "COLCON_IGNORE"
            if not marker.exists():
                click.echo(f"Ignoring {package.name}, not in whitelist", err=True)
                marker.write_text(IGNORE_CONTENT)


def repository_metadata(name: str, repo: Mapping[str, str], path: pathlib.Path) -> dict[str, str]:
    sha = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    url = repo["url"]
    remote_path = url.split(":", 1)[1] if url.startswith("git@") else urlsplit(url).path
    owner = remote_path.strip("/").rsplit("/", 1)[0]
    return {"owner": owner, "repo": name, "sha": sha, "path": str(path)}


def pull_distro_repositories(
    src_dir: pathlib.Path,
    recipes: Mapping[str, Any],
    rosdistro_index: pathlib.Path,
    github_key: str | None = None,
    clean: bool = False,
) -> int:
    """Shallow-clone configured ROS distributions with vcs2l, preserving existing work unless --clean is used."""
    index = rosdistro.get_index(rosdistro_index.resolve().as_uri())
    for distro_name, options in recipes["common"]["distributions"].items():
        distro = rosdistro.get_distribution(index, distro_name)
        repositories, whitelists = select_repositories(distro, options, github_key)
        target_dir = child_directory(src_dir.resolve(), distro_name)
        for name in repositories:
            child_directory(target_dir, name)
        if clean and target_dir.exists():
            click.echo(f"Deleting {target_dir} ...")
            shutil.rmtree(target_dir)
        target_dir.mkdir(parents=True, exist_ok=True)
        for name in repositories:
            path = target_dir / name
            if path.exists() and not (path / ".git").exists():
                raise ValueError(f"{path} is not a Git checkout; move it aside or rerun with --clean")

        click.echo(f"Importing shallow Git checkouts for {distro_name} ...")
        logfile = target_dir / f"{distro_name}_repositories_data.jsonl"
        logfile.unlink(missing_ok=True)
        with tempfile.TemporaryDirectory(prefix="tailor-repositories-") as temp_dir:
            manifest = pathlib.Path(temp_dir) / "sources.repos"
            manifest.write_text(yaml.safe_dump({"repositories": repositories}))
            with github_authentication(github_key):
                result = vcs_import(
                    args=[str(target_dir), "--input", str(manifest), "--shallow",
                          "--skip-existing", "--workers", str(PULL_WORKERS)],
                )
            if result:
                raise RuntimeError(f"vcs2l import failed for {distro_name} (exit code {result})")
        metadata = []
        for name, repo in repositories.items():
            path = target_dir / name
            filter_packages(path, whitelists.get(name, []))
            metadata.append(repository_metadata(name, repo, path))
        logfile.write_text("".join(json.dumps(info) + "\n" for info in metadata))
    return 0


def main():
    parser = argparse.ArgumentParser(description=pull_distro_repositories.__doc__)
    parser.add_argument("--src-dir", type=pathlib.Path, required=True)
    parser.add_argument("--recipes", action=YamlLoadAction, required=True)
    parser.add_argument("--rosdistro-index", type=pathlib.Path, required=True)
    parser.add_argument("--github-key", help="GitHub HTTPS token; otherwise use SSH for GitHub repositories")
    parser.add_argument(
        "--clean", action="store_true", help="Delete configured distribution directories before cloning",
    )
    args = parser.parse_args()
    sys.exit(pull_distro_repositories(**vars(args)))


if __name__ == "__main__":
    main()
