#!/usr/bin/python3
import os
import pathlib
import rosdistro

# from rosinstall_generator.generator import ARG_ALL_PACKAGES, generate_rosinstall

rosdistro_index = pathlib.Path("rosdistro/index.yaml").resolve().as_uri()
os.environ["ROSDISTRO_INDEX_URL"] = rosdistro_index


index = rosdistro.get_index(rosdistro_index)
distro = rosdistro.get_distribution(index, "locus")

for repo in distro.repositories.items():
    print(repo[1])
